name: Build and Test .NET

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List Files for Debugging
      run: ls -R

    - name: Restore Dependencies
      run: dotnet restore ActividadesParamo/ConsoleApp1.sln # Adjust path if necessary

    - name: Build Solution
      run: dotnet build ActividadesParamo/ConsoleApp1.sln --no-restore
