name: Execute Manual Tests with @API Tag

on:
  workflow_dispatch:  # Esto permite ejecutar el flujo manualmente desde la UI de GitHub Actions

jobs:
  manual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment (dotnet, npm, etc.)
        run: |
          # Dependiendo de tu tecnología, instala las dependencias necesarias aquí
          dotnet restore /MockTest/MockTest
          dotnet build /MockTest/MockTest

      - name: Run tests with @API tag
        run: |
          # Ejecuta solo las pruebas etiquetadas con @API en el proyecto específico
          dotnet test /MockTest/MockTest --filter "Category=API"

      - name: Generate test report
        run: |
          # Genera un reporte HTML de los tests
          dotnet test /MockTest/MockTest --logger "html;logfile=test-report.html"

